name: flutter_bluetooth_basic_example
description: Demonstrates how to use the flutter_bluetooth_basic plugin.
publish_to: 'none'

environment:
  sdk: ^3.4.3
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_basic:
    path: ../
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
