name: flutter_bluetooth_basic_updated
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 0.1.8
homepage: https://github.com/andrey-ushakov/flutter_bluetooth_basic

environment:
  sdk: ^3.4.3
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: any
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^4.0.3
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_basic
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin
